### ISSUE TITLE
laravolt/avatar Support

### ISSUE THREAD

**Issue by orlyapps** [davidpiesse/nova-avatars#1]
This Avatar Provider: https://github.com/laravolt/avatar would be great!

**Comment by davidpiesse** [comment]
Started working on this - but can't get it to show up....
Am I doing anything wrong?

```php
return (new \Laravolt\Avatar\Avatar())->create('Users Name')->setDimension(300)->toBase64();
```

**Comment by Krato** [comment]
@davidpiesse Yes. You are calling a Class instead the Facade,

**Comment by davidpiesse** [comment]
Ahhh! 
Laravel Facades 101!
I'll try and get to this tonight. Thanks

**Comment by davidpiesse** [comment]
Added support in commit e24bdda - version 0.0.2

**Comment by orlyapps** [comment]
awesome thanks!
